In [2]:
# 가상 데이터 사용
import torch
import torch.nn as nn
import torch.optim as optim

In [4]:
# 1. 모델, 손실함수 정의
# 10개의 입력 받아서  1개의 값을 예측하는 선형 회귀 모 델
model = nn.Linear(in_features=10,out_features=1)

loss_fn = nn.MSELoss()

In [5]:
# 2.옵티마이저 생성
optimizer = optim.Adam(model.parameters(),lr=0.01) # parameter: = w 
                                                   # 옵티마이저

print(optimizer)


Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    capturable: False
    differentiable: False
    eps: 1e-08
    foreach: None
    fused: None
    lr: 0.01
    maximize: False
    weight_decay: 0
)


In [ ]:
# 3. 가상데이터 생성
input_data = torch.randn(5,10) #데이터는 5개곡 피처는 10개
target_data = torch.randn(5,1)

print(model.weight.data)
#웨이트 초기값이 중요함
#시드를 줘도 그값대로 고정되지 않음

tensor([[-0.1595,  0.0743,  0.2224, -0.1307,  0.2343, -0.1955, -0.1374,  0.1436,
         -0.0037, -0.0917]])


In [8]:
# 4.기울기 초기화(매우 중요)
# 이전 배치의 기울기가 남지 않도록 모든 파라미터의 .grad를 0으로 만드는게 필요함
optimizer.zero_grad()

In [ ]:
# 순전파 및 손실 계산
prediction = model(input_data) # forward()호출함
# 이제 오차값 구할 수 있음

loss = loss_fn(prediction,target_data)
print(f'Calculated Loss: {loss}')

# 기울기 계산

Calculated Loss: 0.5029835104942322


In [ ]:
# 기울기 계산(미분)
loss.backward()

# 파라미터에 적용된 기울기다.
print(model.weight.grad)


tensor([[-0.8862,  0.3911,  0.1679, -0.5290,  0.1266, -0.5921,  0.2829, -0.5895,
         -0.0434, -0.4970]])


In [ ]:
# 7. 파라미터 업데이트
optimizer.step()

# tensor([[-0.1595,  0.0743,  0.2224, -0.1307,  0.2343, -0.1955, -0.1374,  0.1436,
#          -0.0037, -0.0917]])
print(model.weight.data)

tensor([[-0.1395,  0.0543,  0.2024, -0.1107,  0.2143, -0.1755, -0.1574,  0.1636,
          0.0163, -0.0717]])
