In [131]:
# 1.리스트로 텐서 생성
# 0차원 텐서(스칼라)
import torch
from typing import List
scalar_tensor = torch.tensor(7) # 단일값 들어갔으니 스칼라다.
print(scalar_tensor.shape)

torch.Size([])


In [ ]:
# 1차원 텐서는 벡 터
list1d:List[int] = [1,2,3,4]
print(list1d)
print(type(list1d))
tensor_1d = torch.tensor(list1d)
print(tensor_1d)

print(tensor_1d.shape)
print(tensor_1d.ndim)

# 2차원 텐서(행렬)
list2d:List[List[int]] = [[1,2,3,4],[5,6,7,8]]
tensor_2d = torch.tensor(list2d)
print(tensor_2d)
print(tensor_2d.shape)

# 3차원 텐서
list3d:List[List[List[int]]] = [
    [[1,2,3],[4,5,6],[7,8,9]]
]
tensor_3d = torch.tensor(list3d)
print(tensor_3d)
print(tensor_3d.shape) # 즉, "1개의 3×3 행렬을 담고 있는 3차원 텐서"라는 뜻이에요.


[1, 2, 3, 4]
<class 'list'>
tensor([1, 2, 3, 4])
torch.Size([4])
1
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
torch.Size([2, 4])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
torch.Size([1, 3, 3])


In [157]:
# 2.1 ndarray생성(2차원 행렬)
numpy_array = np.array([
    [1.0,2.0,3.0],
    [4.0,5.0,6.0]
],dtype=np.float64

)
print(numpy_array)
print(numpy_array.ctypes.data)

# tensor 변환
tensor_from_numpy = torch.tensor(numpy_array)
print(tensor_from_numpy)
print(tensor_from_numpy.dtype)
print(tensor_from_numpy.data_ptr())

print(numpy_array)
print(numpy_array[0][0])
numpy_array[0][0]=99.0
print(numpy_array[0][0])
print(tensor_from_numpy)
tensor_from_numpy[0][0]=2
print(tensor_from_numpy)

[[1. 2. 3.]
 [4. 5. 6.]]
100675715768064
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
torch.float64
100675871613312
[[1. 2. 3.]
 [4. 5. 6.]]
1.0
99.0
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
tensor([[2., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)


In [161]:
# 3.텐서 속성 확인
# 사용할 장치를 동적으로 설정
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device) # - PyTorch 연산 단위에서는 한 번에 한 디바이스만 지정해야 함

#1.정수리스트를 float32타입의 cpu텐서로 생성
data_int = [1,2,3]
tensor_gpu_float32  = torch.tensor(data_int,dtype=torch.float32,device='cuda')

print(tensor_gpu_float32)
print(tensor_gpu_float32.dtype)

cuda
tensor([1., 2., 3.], device='cuda:0')
torch.float32


In [163]:
# Boolean 텐서를 GPU에 생성
data_bool = [True,False,True]
tensor_gpu_bool = torch.tensor(data_bool,device='cuda')
print(tensor_gpu_bool)
print(tensor_gpu_bool.device)

tensor([ True, False,  True], device='cuda:0')
cuda:0


In [ ]:
# zero랑 onew : 많이쓰임
# 특정크기의 값으로 생성: zeros,ones
zeros_tensor_float32 = torch.zeros(3,4)
print(zeros_tensor_float32)
print(zeros_tensor_float32.dtype)
print(zeros_tensor_float32.device)

zeros_tensor_float321 = torch.zeros(3,4,device='cuda')
print(zeros_tensor_float321.device)

# 2. 2 2 3 크기의 모든 요소가 1인 int8타입의 GPU텐서 생성
ones_tensor_int8 = torch.ones(2,2,3,device='cuda',dtype=torch.int8)
print(ones_tensor_int8)

images_tensor = torch.randn(1,3,256,256)
# print(images_tensor)

# 특정영역지정해서 clip
mask = torch.zeros(256,256,dtype=torch.bool) # 이미지를 덮을 수 있는 마스크를 생성했다
print(mask)

mask[100:150,100:150] = True

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
torch.float32
cpu
cuda:0
tensor([[[1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1]]], device='cuda:0', dtype=torch.int8)
tensor([[False, False, False,  ..., False, False, False],
        [False, False, False,  ..., False, False, False],
        [False, False, False,  ..., False, False, False],
        ...,
        [False, False, False,  ..., False, False, False],
        [False, False, False,  ..., False, False, False],
        [False, False, False,  ..., False, False, False]])


In [212]:
# 시드를 42로 설정
torch.manual_seed(42)# manual은 수동으로 설정,\
rand1 = torch.rand(2,2)
print(rand1)

# 시드 설정없이
rand2 = torch.rand(2,2)
print(rand2)

torch.manual_seed(42)
rand3 = torch.rand(2,2)
print(rand3)

print(rand2)


tensor([[0.8823, 0.9150],
        [0.3829, 0.9593]])
tensor([[0.3904, 0.6009],
        [0.2566, 0.7936]])
tensor([[0.8823, 0.9150],
        [0.3829, 0.9593]])
tensor([[0.3904, 0.6009],
        [0.2566, 0.7936]])


In [217]:
arange_tensor = torch.arange(0,10,2)
print(arange_tensor)

linspace_tensor = torch.linspace(0,10,steps=5)
print(linespace_tensor)

tensor([0, 2, 4, 6, 8])
tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])


In [221]:
original_tensor = torch.randn(2,3,dtype=torch.float64,device='cuda')
print(original_tensor)
print(original_tensor.dtype)
print(original_tensor.device)


tensor([[ 0.6155,  0.1721,  0.2208],
        [ 0.6223, -0.4654,  1.2475]], device='cuda:0', dtype=torch.float64)
torch.float64
cuda:0


In [ ]:
tensor_ = torch.randn(3,5,dtype=torch.float32, device=device, requires_grad=True)