In [26]:
import torch
x = torch.arange(20).reshape(4,5)

print(x)
print('-------------------------------------')
x = torch.arange(20).reshape(4,-1)
print(x)

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])
-------------------------------------
tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])


In [27]:
print(x[1,2])
print(x[2,:])
print(x[:,3])

print(x[1:3,2:4])
mask = x > 10
print(mask)
print(x[mask])

tensor(7)
tensor([10, 11, 12, 13, 14])
tensor([ 3,  8, 13, 18])
tensor([[ 7,  8],
        [12, 13]])
tensor([[False, False, False, False, False],
        [False, False, False, False, False],
        [False,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]])
tensor([11, 12, 13, 14, 15, 16, 17, 18, 19])


In [28]:
# 텐서 이어 붙이기
t1 = torch.arange(6).reshape(2,3)
t2 = torch.arange(6,12).reshape(2,3)

print(t1)
print(t2)

# dim=0 : 행따라 뿥임
cat_dim = torch.cat([t1,t2])
print(cat_dim)

# dim=1 : 열따라 붙ㄱ이기
cat_dim1 = torch.cat([t1,t2],dim=1)
print(cat_dim1)

tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[ 6,  7,  8],
        [ 9, 10, 11]])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
tensor([[ 0,  1,  2,  6,  7,  8],
        [ 3,  4,  5,  9, 10, 11]])


In [29]:
# torch.stack(): 새로운 차원으로 텐서 쌓기
t1 =torch.arange(6).reshape(2,3)
t2 =torch.arange(6,12).reshape(2,3)

stack_dim0 = torch.stack([t1,t2],dim=0)
print(stack_dim0)

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])


In [33]:
print(stack_dim0.shape)

stack_dim1 = torch.stack([t1,t2],dim=1)
print(stack_dim1)

stack_dim2 = torch.stack([t1,t2],dim=2)
print(stack_dim2)

torch.Size([2, 2, 3])
tensor([[[ 0,  1,  2],
         [ 6,  7,  8]],

        [[ 3,  4,  5],
         [ 9, 10, 11]]])
tensor([[[ 0,  6],
         [ 1,  7],
         [ 2,  8]],

        [[ 3,  9],
         [ 4, 10],
         [ 5, 11]]])
